AWSTemplateFormatVersion: '2010-09-09'
Description: ACM Certificate for API Gateway regional custom domain

Parameters:
  Project:
    Type: String
    Description: Logical project identifier (e.g. prompts)
  Owner:
    Type: String
    Description: Resource owner (e.g. olek)
  Stage:
    Type: String
    Description: Deployment stage (e.g. prompts, dev, prod, etc.)
    AllowedValues: [ local, dev, test, prod ]
  DomainName:
    Type: String
    Description: Root domain name (e.g. prompts.com)
  HostedZoneId:
    Type: String
    Description: Route 53 Hosted Zone ID for the root domain

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "api.${DomainName}"
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Sub "api.${DomainName}"
          HostedZoneId: !Ref HostedZoneId
      Tags:
        - Key: Stage
          Value: !Ref Stage
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
        - Key: Region
          Value: !Ref AWS::Region

Outputs:
  CertificateArn:
    Description: ARN of the regional API Gateway certificate
    Value: !Ref Certificate
