name: ${PROJECT_NAME:-prompts}-tests

services:
  web-lambda:
    build:
      context: ./
      dockerfile: web-lambda/Dockerfile
    ports:
      - "${WEB_LAMBDA_PORT}:5000"
    env_file:
      - .env
      - .env.test
    environment:
      APP_STAGE: local
      APP_ENV: test
      APP_DEBUG: 1
      WEB_BASE_URL: "http://web-lambda:5000"
      API_BASE_URL: "http://api-lambda:5000"
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      DYNAMODB_ENDPOINT: "http://dynamodb:8000"
      DYNAMODB_TABLE: app_test
      GOOGLE_ANALYTICS_ID: ""
      TINYMCE_API_KEY: ""
      CONTACT_TOPIC_ARN: ""
      EMAIL_FILES_DIR: "/app-emails"
      STATIC_FILES_DIR: "/app-static"
      PYTHONPATH: "/app:/web-lambda"
      FUNCTION_TEMPLATES_DIR: "/web-lambda/templates"
    volumes:
      - ./shared:/app
      - ./web-lambda:/web-lambda
      - ./static:/app-static
      - ./static:/app/static
      - ./.emails:/app-emails
      - ./.emails:/app/.emails

  api-lambda:
    build:
      context: ./
      dockerfile: api-lambda/Dockerfile
    ports:
      - "${API_LAMBDA_PORT}:5000"
    env_file:
      - .env
      - .env.test
    environment:
      APP_STAGE: local
      APP_ENV: test
      APP_DEBUG: 1
      API_BASE_URL: "http://api-lambda:5000"
      WEB_BASE_URL: "http://web-lambda:5000"
      ALLOWED_ORIGIN: "http://web-lambda:5000"
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      DYNAMODB_ENDPOINT: "http://dynamodb:8000"
      DYNAMODB_TABLE: app_test
      GOOGLE_ANALYTICS_ID: ""
      TINYMCE_API_KEY: ""
      CONTACT_TOPIC_ARN: ""
      EMAIL_FILES_DIR: "/app-emails"
      STATIC_FILES_DIR: "/app-static"
      PYTHONPATH: "/app:/api-lambda"
      FUNCTION_TEMPLATES_DIR: "/api-lambda/templates"
    volumes:
      - ./shared:/app
      - ./api-lambda:/api-lambda
      - ./static:/app-static
      - ./static:/app/static
      - ./.emails:/app-emails
      - ./.emails:/app/.emails

  tests:
    build:
      context: ./
      dockerfile: tests/Dockerfile
    command: [ "tail", "-f", "/dev/null" ]
    depends_on:
      - dynamodb
    env_file:
      - .env
      - .env.test
    environment:
      PYTHONPATH: "/tests:/scripts"
      WEB_TEST_BASE_URL: "http://web-lambda:5000"
      API_TEST_BASE_URL: "http://api-lambda:5000"
      TEST_DYNAMODB_TABLE: app_test
      PROJECT_ROOT: "/project"
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      DYNAMODB_ENDPOINT: "http://dynamodb:8000"
    volumes:
      - ./tests:/tests
      - ./:/project
      - ./scripts:/scripts
      - ./static:/app/static
      - ./.emails:/app/.emails

  dynamodb:
    image: amazon/dynamodb-local
    user: root
    ports:
      - "${DYNAMODB_PORT}:8000"
    volumes:
      - dynamodb-test-data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"

volumes:
  dynamodb-test-data:
