"""Canonical API route names and path templates."""

API_URL_ROUTES = {
    "upload-public-file": "/public-file",
    "create-prompt": "/prompts",
    "prompts-fragment": "/prompts-fragment",
    "prompt-comments-fragment": "/prompts/{prompt_id}/comments-fragment",
    "update-prompt": "/prompts/{prompt_id}",
    "update-prompt-status": "/prompts/{prompt_id}/status",
    "update-prompt-impression": "/prompts/{prompt_id}/impression",
    "create-prompt-comment": "/prompts/{prompt_id}/comment",
    "update-prompt-comment": "/prompts/{prompt_id}/comments/{comment_id}",
    "create-contact-message": "/contacts/message",
    "get-tag-subscriptions": "/tag-subscriptions",
    "create-tag-subscription": "/tag-subscriptions",
    "delete-tag-subscription": "/tag-subscriptions/{tag_subscription_id}",
    "update-tag": "/tags/{slug}",
    "get-tags": "/tags",
    "tags-fragment": "/tags-fragment",
    "users-fragment": "/users-fragment",
    "update-user-status": "/users/{user_id}/status",
    "update-user-impression": "/users/{user_id}/impression",
    "update-user-activity-settings": "/users/{user_id}/activity-settings",
    "update-user-interests-settings": "/users/{user_id}/interests-settings",
    "update-user": "/users/{user_id}",
    "user-prompts-fragment": "/users/{user_id}/prompts-fragment",
    "generate-sitemap": "/generate-sitemap",
    "drop-cdn-cache": "/drop-cdn-cache",
}
