"""Canonical web route names and path templates."""

WEB_URL_ROUTES = {
    "index": "/",
    "new-prompt": "/prompts/new",
    "prompts": "/prompts",
    "tags": "/tags",
    "prompt": "/prompts/{prompt_id}",
    "edit-prompt": "/prompts/{prompt_id}/edit",
    "prompts-by-slugs": "/{slugs_path:path}/prompts",
    "legacy-posts": "/posts",
    "legacy-singular-prompts": "/post",
    "legacy-new-prompt": "/posts/new",
    "legacy-singular-new-prompt": "/prompt/new",
    "legacy-prompt": "/posts/{prompt_id}",
    "legacy-singular-prompt": "/post/{prompt_id}",
    "legacy-edit-prompt": "/posts/{prompt_id}/edit",
    "legacy-singular-edit-prompt": "/prompt/{prompt_id}/edit",
    "legacy-posts-by-slugs": "/{slugs_path:path}/posts",
    "contacts": "/contacts",
    "edit-tag": "/tags/{slug}/edit",
    "users": "/users",
    "users-by-slugs": "/{type}/users",
    "user": "/users/{user_id}",
    "edit-user": "/users/{user_id}/edit",
    "login": "/login",
    "login-callback": "/login-callback",
    "logout": "/logout",
    "logout-callback": "/logout-callback",
    "policy": "/privacy-policy",
    "rules": "/rules",
    "terms": "/terms-of-service",
    "earn": "/earn-with-us",
    "utils": "/utils",
    "user-by-slug": "/{slug}",
    "prompt-by-slugs": "/{user_slug}/{prompt_slug}",
}
